### ISSUE TITLE
security groups

### ISSUE THREAD

**Issue by blackjid** [terraform-community-modules/tf_aws_ec2_instance#3]
How can I add attach some security groups to the created instances???

**Comment by ktseytlin** [comment]
@blackjid 

If you want to add security groups, here are the steps:

First, edit your variables file - variables.tf

```
variable "machine_securitygroups" {
  description = "The security groups for machine."
  default = "sg-xxxxxxxx"
}
```

Next, edit your main file - main.tf

```
resource "aws_instance" "kafka" {
...
  vpc_security_group_ids = ["${var.machine_securitygroups}"]
...
}
```

This should work out for you like this.

**Comment by ktseytlin** [comment]
Also, I believe this issue can be closed out.
